language: php

php:
  - 5.4

before_script:
  - sudo apt-get install php5-dev php5-xdebug
  - composer install --dev --no-interaction --prefer-source

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 libraries app
  - php vendor/bin/phpunit --configuration tests/phpunit.xml
  #- php vendor/bin/phpmd library text codesize,unusedcode,naming
  #- php vendor/bin/phpdcd -n library
  #- php vendor/bin/phpcpd -n --progress library